### ISSUE TITLE
Input field standardization for AA calculator

### ISSUE THREAD

**Issue by appuk** [RedHatInsights/tower-analytics-frontend#131]
This ticket tracks conversation related to the following changes and how to address them:
1. the manual and automation cost should not accept negative values
2. the fields should accept decimal values.
currently, it does accept the values, but a `invalid input tooltip` is displayed when you hover over the text field

<img width="300" alt="Screen Shot 2020-04-21 at 5 00 19 PM" src="https://user-images.githubusercontent.com/11617351/80019606-cf438380-84a5-11ea-957e-69817a730f5c.png">

**Comment by appuk** [comment]
The issues listed above seem to be fixed,
But, for the text fields `manual cost` and `cost of automation` , the user can enter a negative value but the app throws an error
and for the `template time` in top templates, the user just cannot enter a negative value
so the behavior is different for both the text fields
it would be great to make this consistent

**Comment by wenottingham** [comment]
@appuk is this resolved in production now?

**Comment by appuk** [comment]
@jeanetteobr The behavior is still inconsistent and the user can still enter negative values:
<img width="352" alt="Screen Shot 2020-07-07 at 12 12 46 PM" src="https://user-images.githubusercontent.com/11617351/86810959-681c8080-c04b-11ea-998b-f00b0e96fc93.png">

looks like marking it as parseFloat did not fix the issue

**Comment by brumik** [comment]
@appuk That commit should fix it

**Comment by jeanetteobr** [comment]
@brumik Are we OK to close this issue?

**Comment by brumik** [comment]
No, the PR is still open which is fixing this.

**Comment by jctanner** [comment]
migrated to https://issues.redhat.com/projects/AA/issues/AA-149
